### ISSUE TITLE
How do you produce the .vsix file?

### ISSUE THREAD

**Issue by markfirmware** [zigtools/zls-vscode#1]

**Comment by SuperAuguste** [comment]
Sorry for the late response!

According to the VSCode docs:
```bash
# Install vsce if not installed
$ npm install -g vsce

# Package extension
$ cd zig-lsc
$ vsce package
```

**Comment by markfirmware** [comment]
I get

    ERROR  Missing publisher name. Learn more: 

See #2

**Comment by SuperAuguste** [comment]
My bad! Didn't get the `package.json` filled out right! I'm going to fix that right away!

**Comment by SuperAuguste** [comment]
You can find the `vsix` file [on the releases page](https://github.com/zigtools/zls-vscode/releases/tag/1.0.0) now! Thanks so much for your help with this issue!
