### ISSUE TITLE
maybe explain more clearly the VSCode setting..

### ISSUE THREAD

**Issue by ffred** [zigtools/zls-vscode#11]
sorry, could be because English is not my native language, but as I first understand it, I thought I just have to set the path to the zls.exe file in the VSCode ZLS setting, but every thing I tried give the error : 
"Couldn't start client Zig Language Server Client".

until I realize that it's not the path that is needed, but the command to launch zls......
maybe  the text about VSCode setting could be made clearer about that, for the next newcomers.
thanks.

**Comment by SuperAuguste** [comment]
Hey @ffred! I totally agree with your analysis! I thought that the current description (`Path to \`zls\` executable.`) was clear enough, but now that I read it over, it does seem to imply the *directory* of the `zls` executable. I'll change this soon and update the version available on the store!

**Comment by SuperAuguste** [comment]
I changed the description to `Path to zls executable. Example: C:/zls/zig-cache/bin/zls.exe.`, which should clarify things. Thanks for your issue! :)
