### ISSUE TITLE
Could not start language server command 'zls.start' not found

### ISSUE THREAD

**Issue by creikey** [zigtools/zls-vscode#16]
When I try to start the language server from vscode I get an error that says:

```Command 'Zig Language Server: Start Zig Language Server' resulted in an error (command 'zls.start' not found)```

**Comment by Diegovsky** [comment]
What version are you using?

**Comment by thatcosmonaut** [comment]
Can confirm this is an issue on extension versions past 1.0.1

**Comment by Diegovsky** [comment]
can confirm happening in 1.0.4

**Comment by aliak00** [comment]
Also with 0.1.8

**Comment by SuperAuguste** [comment]
Occurs when the server exits before registering commands (e.g. the provided zls executable path is invalid); fix on its way
