### ISSUE TITLE
Duplicate info in the code completion popup

### ISSUE THREAD

**Issue by RUSshy** [zigtools/zls-vscode#18]
As you can see here: 

![image](https://user-images.githubusercontent.com/18348637/97899341-7cdafd80-1d39-11eb-8cf3-e47e930e2a2d.png)

The field name is seen twice, wich causes the type to be truncated.. wich is not very helpful, specially when the duplicated name is very long, like this: 

![image](https://user-images.githubusercontent.com/18348637/97899482-a4ca6100-1d39-11eb-9167-b143839fd340.png)

**Comment by alexnask** [comment]
Hm, weird bug, I will look into it.  
This should probably be an issue in the zls repository instead though :)
