### ISSUE TITLE
Add support for `~` in `zigLanguageClient.path`

### ISSUE THREAD

**Issue by OoLunar** [zigtools/zls-vscode#19]
When attempting to do `~/Code/zls/zig-cache/bin/zls`, the extension fails with 
```
[Error - 12:51:26 PM] Starting client failed
Launching server using command ~/Code/zls/zig-cache/bin/zls failed.
```

Perhaps show the error next time? Solution was `/home/lunar/Code/zls/zig-cache/bin/zls`

**Comment by gkiely** [comment]
Same issue I was pointing to `~/zls/zls` and couldn't figure out why it wasn't starting.

I realize this is a separate issue but it would be great if zls just printed out the correct path after running configure.
<img width="673" alt="image" src="https://user-images.githubusercontent.com/1948935/163683646-eb0a54c5-0fb4-4bea-b7da-10acb0abb919.png">
