### ISSUE TITLE
Add build instructions

### ISSUE THREAD

**Issue by BinaryWarlock** [zigtools/zls-vscode#21]
The README offers no hint on how to build and install the extension locally.

In addition: How do you package it to a .VSIX?

**Comment by prime31** [comment]
The project is made directly from the VS Code extension template. If you open it in VS Code all the default build, watch and packaging tasks are in the usual locations.

**Comment by fivemoreminix** [comment]
> 
> 
> The README offers no hint on how to build and install the extension locally.
> 
> In addition: How do you package it to a .VSIX?

Were you able to get the extension installed and working? I am going to improve the install experience.

**Comment by fivemoreminix** [comment]
@BinaryWarlock On the ZLS wiki, it explains how to download and compile ZLS. There's also a page about configuring it with Visual Studio Code. https://github.com/zigtools/zls/wiki/Downloading-and-Building-ZLS

**Comment by BinaryWarlock** [comment]
@fivemoreminix I ended up downloading the .VSIX from the extension marketplace ([here](https://marketplace.visualstudio.com/items?itemName=AugusteRame.zls-vscode), "Download Extension" on the right in case anyone is wondering). I can't browse it from within VSCode because I use Codium (see #20).

ZLS was easy to install, I'm just unfamiliar with the VSCode extension build process, so adding a quickstart to the README might benefit people.

**Comment by fivemoreminix** [comment]
For sure, that would be very helpful.
