### ISSUE TITLE
The zls.json should be configurable from within the extension settings in the editor

### ISSUE THREAD

**Issue by fivemoreminix** [zigtools/zls-vscode#24]
For the sole purpose of ease of use.

**Comment by alexnask** [comment]
Yeah, thsi would be nice.  
Especially if I reintroduce the workspace specific configuration at some point.

**Comment by oopsmonk** [comment]
any update?
it's useful, say I work with different zig releases but need to manually modify the `zig_lib_path` in zls.json. otherwise, the extension complains `Unable to open 'std.zig': Unable to read file ...`

**Comment by SuperAuguste** [comment]
@fivemoreminix @oopsmonk Your wish has been realized (well half of it anyways, zigtools/zls#520 still needs to land); enjoy!
