### ISSUE TITLE
Supply LanguageClientOptions.connectionOptions.maxRestartCount set to some high value to work around ZLS crash issues

### ISSUE THREAD

**Issue by 20kdc** [zigtools/zls-vscode#28]
ZLS crashes often here. When ZLS restarts, it's usually fine again. When ZLS crashes enough times, however, it becomes unusable, because apparently if a language server crashes enough times the default VSCode behaviour is to turn it off,.
In practice this "recovery" behaviour basically makes ZLS unusable.

Reproduction method: Write code until ZLS breaks. IDK.
Version of ZLS used: 0.9.0
Version of Zig used: Master `https://ziglang.org/builds/zig-linux-x86_64-0.10.0-dev.183+5c228765f.tar.xz`
Version of extension used: 1.0.0, also seen with integrated ZLS support in prime31 zig support extension.

**Comment by SuperAuguste** [comment]
VSCode disabling ZLS after a while is intended behavior; ZLS isn't meant to crash so I'll work on fixing the crashing instead of implementing a workaround. :)
