### ISSUE TITLE
Release versions confusion

### ISSUE THREAD

**Issue by WizardUli** [zigtools/zls-vscode#36]
VSCode marketplace is showing that the latest version is 1.0.4
`README.md` in this repo mentions version 1.0.2

But I cannot find any information about which commits were those releases built from. There are no respective tags in the repo and github releases page has only 1.0.0 version.
Same issue as #25 which was closed without any answer.

**Comment by truemedian** [comment]
1.0.3 is https://github.com/zigtools/zls-vscode/commit/cf7d4499d9890e2aef9ef5cce88eeaed9bd123d2
1.0.4 is https://github.com/zigtools/zls-vscode/commit/3bcca8e256f34a8cdb1578fd0f7fdfc0def56a12

Would be nice if they were tagged though, looking through blame is weird for version information

**Comment by SuperAuguste** [comment]
https://github.com/zigtools/zls-vscode/tree/1.0.5!
