### ISSUE TITLE
Publish This on VS Code Extensions Marketplace

### ISSUE THREAD

**Issue by codemessiah** [zigtools/zls-vscode#4]
I see you have a 1.0 release available here, but many people are not looking for your extension on GitHub, they're searching for something good on the extensions marketplace. It would be a really good idea to add it as soon as possible to the extensions marketplace so you can begin obtaining ratings, users, and feedback.

Hello, love the project. I know ZERO about language servers, but I have wanted to work on one for Zig for over a year now. I own the Zig Discord server. My username is Code Messiah#1024 I'd love to talk with you.

**Comment by SuperAuguste** [comment]
Hey @codemessiah! Great call on publishing the extension! I'll definitely have to look into that. I'd love to talk to you about language server anytime, and you can feel free to make a PR with any changes you see fit!

**Comment by SuperAuguste** [comment]
Looks good!

https://marketplace.visualstudio.com/items?itemName=AugusteRame.zls-vscode
