### ISSUE TITLE
Install server command failed with ENOENT: no such file or directory, mkdir '[...]'

### ISSUE THREAD

**Issue by mjoork** [zigtools/zls-vscode#43]
The install command is failing with an uncaught error: 
```
ENOENT: no such file or directory, mkdir 'c:\Users\mark\AppData\Roaming\Code\User\globalStorage\augusterame.zls-vscode\zls_install'
```

![Runtime Status tab](https://user-images.githubusercontent.com/20644474/178836630-1bbab21d-72e6-4ab8-9656-198cefc295bf.png)

The output log just states failing to start the server:

```
[Error - 11:09:28 PM] Zig Language Server client: couldn't create connection to server.
Error: Unsupported server configuration {
    "command": "",
    "args": []
}
	at c:\Users\mark\.vscode\extensions\augusterame.zls-vscode-1.1.0\node_modules\vscode-languageclient\lib\node\main.js:464:35
	at async LanguageClient.createConnection (c:\Users\mark\.vscode\extensions\augusterame.zls-vscode-1.1.0\node_modules\vscode-languageclient\lib\common\client.js:1052:28)
	at async LanguageClient.start (c:\Users\mark\.vscode\extensions\augusterame.zls-vscode-1.1.0\node_modules\vscode-languageclient\lib\common\client.js:617:32)
```

**Comment by mjoork** [comment]
I found the issue. Sorry for opening this, but maybe will be helpful for someone.

The problem was in my terminal multiplexer - [cmder](https://github.com/cmderdev/cmder). When using full installation, cmder creates some aliases for some commands to mimic *NIX commands, so when you run VSCode from cmder using `code`, it was invoking a unix command `mkdir` without `-p`.

**Comment by mjoork** [comment]
I tried replicating that it works when VSCode isn't run from inside cmder. The issue is not resolved. It still fails with the same error. Creating a directory manually helps though.

P.S.: I kindly apologize for doing so much actions on this issue in a short amount of time.

**Comment by SuperAuguste** [comment]
Thanks for opening an issue! It's definitely not a terminal related issue as we're using the mkdir syscall through node's fs rather than a terminal command; the fix for this is adding mkdirp to the extension; I'll fix it tomorrow!

**Comment by SuperAuguste** [comment]
Try using the extension now, this issue should be fixed!

**Comment by mjoork** [comment]
Thank you, unfortunately can't test it right now, but I believe you that it was fixed.
