### ISSUE TITLE
Auto complete doesn't seem to work in vscode

### ISSUE THREAD

**Issue by elgs** [zigtools/zls-vscode#47]
zls-vscode version: v1.1.2
zig version: 0.9.1

I expect after typing a dot the member variables/methods will be shown in a pop up list, but it doesn't.

**Comment by SuperAuguste** [comment]
Please provide more information such as an example of broken code :)

**Comment by elgs** [comment]
Just as simple as:
```zig
const std = @import("std");

pub fn main() !void {
  std.
}
```
When the dot is typed, I expect an auto complete pop up, but it doesn't.

But I figured out the problem is zls on 0.9.0.

I was able to get it work to build zls from source, using:
```
git clone --recurse-submodules https://github.com/zigtools/zls
cd zls
zig build -Drelease-safe
./zig-out/bin/zls config # Configure ZLS
```

However, zig 0.9.1 cannot compile the latest code of zls at this very moment of time. So I had to use HEAD version of zig by:

```
brew install zig --HEAD
```

**Comment by SuperAuguste** [comment]
Ah ok, good to know! I would generally recommend using the HEAD version of zig instead of 0.9.1 but that's all up to you.

**Comment by elgs** [comment]
I am not a hardcore zig user yet. The reason I am not using zig HEAD is I upgrade my brew packages daily. I expect I would get a lot of zig updates which requires building from the source if I'd use the HEAD. I wish zig will release more frequently.
