### ISSUE TITLE
Issues with m1 mac

### ISSUE THREAD

**Issue by lecoqjacob** [zigtools/zls-vscode#48]
I installed zig from master then installed ZLS from master, but every-time i open VScode, it fails to find ZLS in my path.

<img width="494" alt="CleanShot 2022-08-28 at 16 24 27@2x" src="https://user-images.githubusercontent.com/9278174/187095093-c08ead3b-774c-45b2-a3a8-7007cfa855d2.png">

<img width="307" alt="CleanShot 2022-08-28 at 16 28 12@2x" src="https://user-images.githubusercontent.com/9278174/187095204-9da6549b-d07a-4d0e-ad69-7325420ebfd2.png">

I had to specifically go into vscode settings and set the `zls.path` for it to pick up correctly

**Comment by hhstore** [comment]
- The latest version (v1.1.3) of the zls-vscode plugin has bugs and can never find zls.  
- It is recommended to fall back to the v1.1.2 version to use.  
- v1.1.2 is normal.


![image](https://user-images.githubusercontent.com/3252130/189403722-88beebb1-1e37-43d5-bc75-d26bcd8ff482.png)

> my env:


```
➤ zig version
0.10.0-dev.2617+47c4d4450


```

**Comment by SuperAuguste** [comment]
> The latest version (v1.1.3) of the zls-vscode plugin has bugs and can never find zls.

Could you open a new issue about this?
