### ISSUE TITLE
zls installation failed because of broken url

### ISSUE THREAD

**Issue by jkzing** [zigtools/zls-vscode#51]
The original issues is, after installing the extension zls cannot be started with this output:

![CleanShot 2022-09-05 at 20 52 20](https://user-images.githubusercontent.com/2851517/188453729-7d2f050d-a0af-4713-87cf-144e3047388b.png)

According to the code here https://github.com/zigtools/zls-vscode/blob/master/src/extension.ts#L61

I believe the reason is those urls are broken:

https://zig.pm/zls/downloads/i386_linux/bin/build_runner.zig
https://zig.pm/zls/downloads/i386_windows/bin/build_runner.zig
https://zig.pm/zls/downloads/x86_64_linux/bin/build_runner.zig
https://zig.pm/zls/downloads/x86_64_macos/bin/build_runner.zig
https://zig.pm/zls/downloads/x86_64_windows/bin/build_runner.zig

In my case, it is https://zig.pm/zls/downloads/x86_64_macos/bin/build_runner.zig

**Comment by SuperAuguste** [comment]
Yep, this is because of the new <https://github.com/zigtools/zls/pull/624> change. I'll commit a fix ASAP and release a new version :)
