### ISSUE TITLE
Commands depend on invalid command line arguments of `zls`

### ISSUE THREAD

**Issue by HymanZHAN** [zigtools/zls-vscode#53]
My zls config generated by `zls config`:

```json
{
  "zig_exe_path": "/home/xzhan/Development/Packages/software/zig/zig",
  "zig_lib_path": "/home/xzhan/Development/Packages/software/zig/lib",
  "enable_snippets": true,
  "warn_style": true,
  "enable_semantic_tokens": true,
  "operator_completions": true,
  "include_at_in_builtins": false,
  "max_detail_length": 1048576
}
```

I installed zls manually (following [this instruction](https://github.com/zigtools/zls#linux)) for use inside NeoVim and VS Code. However, when I tried to start the server by invoking "Zig Language Server: Start Server," I was greeted by 
an error:

![image](https://user-images.githubusercontent.com/26806995/193400788-2ee96f3c-f462-4b42-b120-7cc92fde3fc2.png)

![image](https://user-images.githubusercontent.com/26806995/193400031-d9c3d7d0-3a54-44af-85fd-c1fcdfc49ac5.png)

The same goes for "Zig Language Server: Open ZLS Config":

![image](https://user-images.githubusercontent.com/26806995/193400799-57e74813-e7f3-4482-bf73-ac39f557d468.png)

**Comment by Techatrix** [comment]
zls-vscode assumes you are using a build from master and not the old 0.9.0 release which is very outdated and should only be used if you are using the 0.9.x zig compiler as well.
You can either compile from source yourself ([instructions](https://github.com/zigtools/zls#from-source)) or use the command `Zig Language Server: Install Server` in vs-code which installs the latest prebuild binary for you.

**Comment by HymanZHAN** [comment]
Thanks for the clarification! I guess this "assumption" could be mentioned somewhere in the README, though.
