### ISSUE TITLE
Command 'Zig Language Server: Start Server' resulted in an error (Request failed with status code 403)

### ISSUE THREAD

**Issue by elgs** [zigtools/zls-vscode#54]
Got the following error when starting 

```
Command 'Zig Language Server: Start Server' resulted in an error (Request failed with status code 403)
```

vscode config:
```
"zls.path": "/Users/qianchen/Library/Application Support/Code/User/globalStorage/augusterame.zls-vscode/zls_install/zls",
```

```
~/code/zig/hello$ zig version
0.10.0

~/code/zig/hello$ which zig
/opt/homebrew/bin/zig
```
```
Zig Language Server (zls) for VSCode
v1.1.4
```

<img width="913" alt="Screenshot 2022-11-01 at 9 28 28 PM" src="https://user-images.githubusercontent.com/55955/199396287-59e3e9f6-f413-4c52-9b0d-52a5d8e8416d.png">

**Comment by SuperAuguste** [comment]
403 seems to indicate an issue with the autoupdater fetching the zls binary; manually replicating this doesn't lead to an issue... Are there any errors logged in the VSCode Inspect Elements console related to this? (like a `fetch` or `XHR` failure of some sort?) :)

**Comment by elgs** [comment]
Thanks for the quick reply! I got this in the dev console.

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/55955/199400497-b06c8489-c2ad-4749-9257-359cdec2054e.png">

**Comment by SuperAuguste** [comment]
Could you try to hunt down the URL being requested, maybe looking for request failures in the Network tab>

**Comment by elgs** [comment]
The 403 error only happened when I reinstall the zls extension. Also there is no 403 response from the network tab. When I manually restart the zls server, neither the dev console nor the network tab has any output.

https://goweb.az.ht/tmp/zls_error.gif

**Comment by SuperAuguste** [comment]
I tried replicating this issue locally but I couldn't achieve it; unfortunately your GIF doesn't really give me enough information to go off of. Would you mind joining the zls Discord (see README) so we could debug this live?

**Comment by elgs** [comment]
I couldn't figure out how to do the Discord, as I didn't find it from the README. I opened a Google Meet here in case you could join.

https://meet.google.com/fyo-rpgn-hvt

**Comment by SuperAuguste** [comment]
Could you please update the extension to the latest version, remove the `check_for_update` line in your settings and try this again? Just pushed and published a definitive fix (hopefully) :)

**Comment by elgs** [comment]
Updated to v1.1.5, and removed `check_for_update`. I still got the 403 dialog.

**Comment by elgs** [comment]
When I restart the zls server, I got this message:

<img width="448" alt="image" src="https://user-images.githubusercontent.com/55955/199411894-9722631f-f925-4398-8754-1f4b8ac41f9e.png">

**Comment by SuperAuguste** [comment]
That's totally normal :)

So along with the 403, are there multiple "Installing zls..." windows like before?

**Comment by elgs** [comment]
The multiple "Installing zls..." windows is not showing up any more. :)

**Comment by SuperAuguste** [comment]
Okay; I think you might just be rate limited because the bug I just fixed caused your client to send too many requests to the `zig.pm` server

Could you try again tomorrow and see what happens?

**Comment by elgs** [comment]
I disconnected from the vpn, and it works!! Thank you so much! it looks like the update server is not happy with the vpn server ip I was using. :)

One thing I observed which doesn't affect the functionality is upon each start of vscode, I saw the "Installing zls ..." message once, and followed by the "ZLS has been build(t) with a newer versionthan ..." message.

**Comment by SuperAuguste** [comment]
Yep, that's intended functionality, albeit a little annoying.

Thank you so much for bearing with me and helping me hunt this down!
