### ISSUE TITLE
Zls fails to start if automatic updates are enabled

### ISSUE THREAD

**Issue by Avokadoen** [zigtools/zls-vscode#58]
The title says it all. It should be easy to reproduce. Simply try to start zls through vscode without an internet connection

**Comment by BuzzwordChief** [comment]
On Windows it will also cause zls to not function at all regardless of the internet connection. If I have automatic updates enabled I get this error after restarting vscode:
![image](https://user-images.githubusercontent.com/11695209/210028991-6002b133-775e-45b9-a016-0595eeddeeaf.png)

After I disabled the feature zls works perfectly fine again!

**Comment by SuperAuguste** [comment]
@BuzzwordChief Could you post your extension logs / any network errors in the Developer Tools console window please?
