### ISSUE TITLE
zls-vscode doesn't start until tiehuis.zig extension is installed and running

### ISSUE THREAD

**Issue by ghost** [zigtools/zls-vscode#6]
For ZLS to start, .zig files need to be associated with the "zig" lanuage mode which zls-vscode doesn't do by itself so you need to have the tiehuis.zig extension running as well. This is not mentioned in README.md. Is this a bug or is it intended that you need both this extension and tiehuis.zig?

**Comment by SuperAuguste** [comment]
Hi @DEC05EBA! `zls-vscode` is intended to be used with other zig extensions! This should definitely be mentioned in the README, and I'll fix that as soon as possible.

**Comment by markfirmware** [comment]
This would be needed in zls-vscode for it to not be dependent on vscode-zig:

https://github.com/ziglang/vscode-zig/blob/263fad632405a85d4f1cc322243752e734660db6/package.json#L24-L29

**Comment by alexnask** [comment]
@markfirmware We may do this once we get semantic token hihglighting working.

**Comment by SuperAuguste** [comment]
This should be fixed in the latest version - I'll push to the store again in a few minutes just to make sure! Feel free to reopen this issue if the change doesn't go through!
